proj_setup <- function(path, ...) {

  # Create directories
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Data"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Data/Raw"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Data/Processed"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Analysis"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Documentation"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Reports"), recursive = TRUE, showWarnings = FALSE)

  # create some header text
  header <- c(
    "# GL Management Unit Project",
    "*project template generated by* `GLReportR`"
  )

  instructions <- c(
    "# GL Managment Unit Project Template Intructions",
    "## Folder Description and Contents",
    "File | Description",
    "---------- | --------------------------------------------------",
    "Data | contains the project data in subdirectories",
    "Data/Raw | Raw data as collected should be stored here./nIf applicable, this data should match paper copies",
    "Data/Processed | Data that has been cleaned and mapped to the template data base",
    "Analysis | Analysis and data scrubbing scripts",
    "Documentation | Project documentation files such as survey protocols and data management plan",
    "Reports | Markdown report files or other file formats used to report on the project",
    "<hr />",
    "<br />",
    "  ",
    "<!-- This file is best viewed using the RStudio previewer -->",
    "  ",
    "### *This file can be deleted following project set up.*",
    "  ",
    "<hr />"
  )

  writeLines(instructions, con = file.path(path, "Instructions.md"))

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val, "<br />")
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "  \n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "ReadMe.md"))
}
